INHERIT: base.yml
site_name: CCS Specifications (2023-06)
nav:
- Contest Control System specifications: readme.md
- CCS System Requirements: Contest_Control_System_Requirements.md
- Contest API: Contest_API.md
- Contest Package Format: Contest_Package.md
